export const sidebarIcons = [
  {
    id: 0,
    name: "New Sale",
    button: true,
    icon: "app/assets/icons/cart-shopping-solid-full.svg",
  },
  {
    id: 1,
    name: "New Item",
    button: true,
    icon: "app/assets/icons/qrcode-solid-full.svg",
  },
  {
    id: 2,
    name: "Activity",
    button: false,
    category: "general",
    icon: "app/assets/icons/bell-solid-full.svg",
  },
  {
    id: 3,
    name: "Dashboard",
    button: false,
    category: "general",
    icon: "app/assets/icons/grip-solid-full.svg",
  },
  {
    id: 4,
    name: "Users",
    button: false,
    category: "general",
    icon: "app/assets/icons/users-solid-full.svg",
  },
  {
    id: 5,
    name: "Products",
    button: false,
    category: "shop",
    icon: "app/assets/icons/boxes-stacked-solid-full.svg",
  },
  {
    id: 6,
    name: "Lookup",
    button: false,
    category: "shop",
    icon: "app/assets/icons/magnifying-glass-dollar-solid-full.svg",
  },
  {
    id: 7,
    name: "Reports",
    button: false,
    category: "shop",
    icon: "app/assets/icons/square-poll-vertical-solid-full.svg",
  },
  {
    id: 8,
    name: "Settings",
    button: false,
    category: "support",
    icon: "app/assets/icons/gear-solid-full.svg",
  },
  {
    id: 9,
    name: "Support",
    button: false,
    category: "support",
    icon: "app/assets/icons/headset-solid-full.svg",
  },
];
